/*
 * DO NOT EDIT.
 *
 * Generated by the protocol buffer compiler.
 * Source: _MeasureRepeat.proto
 *
 */

import Foundation
import SwiftProtobuf


struct _MeasureRepeat: SwiftProtobuf.Message, SwiftProtobuf.Proto3Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf.ProtoNameProviding {
  public var swiftClassName: String {return "_MeasureRepeat"}
  public var protoMessageName: String {return "MeasureRepeat"}
  public var protoPackageName: String {return "_"}
  public static let _protobuf_fieldNames = FieldNameMap()


  init() {}

  public mutating func _protoc_generated_decodeField(setter: inout SwiftProtobuf.FieldDecoder, protoFieldNumber: Int) throws {
  }

  public func _protoc_generated_traverse(visitor: inout SwiftProtobuf.Visitor) throws {
  }

  public func _protoc_generated_isEqualTo(other: _MeasureRepeat) -> Bool {
    return true
  }
}
